language: cpp

branches:
  only:
    - master

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config
    - libcurl4-openssl-dev

# Build steps
script:
  - ./build_simple.sh
  - cd ./tests/
  - ./run_package_installation.sh
  - cd ..
  - cd unit-tests.wsjcpp
  - ./build_simple.sh
  - ./unit-tests