language: cpp

branches:
  only:
    - master
    - dev

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config
    - libcurl4-openssl-dev

# Build steps
script:
  - ./ci/travis/run.sh